id: A95849494
title: Guru Sādhana of Glorious Dharmakīrti
type: translation
pechas:
- I42E3A302
- IB37C3BB5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:20.476510
  last_modified_at: 2023-01-04 12:12:20.476516
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I42E3A302/6355: 646B
  IB37C3BB5/F89E: 646B
